version: '3.8'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - nuxt_network

networks:
  nuxt_network:
    driver: bridge
