version: '3.8'

services:
  nuxt:
    image: node:20 # Node.js Docker image
    working_dir: / # Set the working directory inside the container
    volumes:
      - /:/ # Bind the app directory to the container
    command: npm run dev # Default command to start Nuxt.js in development mode
    ports:
      - "3000:3000" # Expose port 3000 for Nuxt.js app
    environment:
      - NODE_ENV=development
    networks:
      - nuxt_network
  # You can add other services like databases, caches, etc. if needed.

networks:
  nuxt_network:
    driver: bridge
