version: '3.8'

services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/
      - /node_modules
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "preview"]
