version: 2.1

jobs:
  build:
    docker:
      - image: node:18  # Use the official Node.js image instead of circleci/node
    steps:
      - checkout
      - run:
          name: Check Node.js Version
          command: node -v
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Prepare Nuxt
          command: npx nuxt prepare
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Nuxt Project
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

