version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.16  # CircleCI Node.js image
    working_directory: ~/

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Set up Docker
          command: |
            docker --version
            docker-compose --version

      - run:
          name: Build Docker image
          command: |
            docker-compose -f docker-compose.yml build

      - run:
          name: Run tests (if any)
          command: |
            docker-compose -f docker-compose.yml run nuxt npm run test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Set up Docker and Docker Compose
          command: |
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
