version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.16  # CircleCI Node.js image
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    docker:
      - image: docker:19.03.12  # Docker image (not DinD)
    services:
      - docker  # Adds the Docker service to the job
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Set up Docker
          command: |
            docker --version
            docker-compose --version

      - run:
          name: Build Docker image
          command: |
            docker-compose -f docker-compose.yml build

      - run:
          name: Run tests (if any)
          command: |
            docker-compose -f docker-compose.yml run nuxt npm run test

  deploy:
    executor: node-executor
    docker:
      - image: docker:19.03.12
    services:
      - docker  # Adds the Docker service to the deploy job
    steps:
      - checkout
      - run:
          name: Set up Docker and Docker Compose
          command: |
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d

services:
  docker:
    image: docker:19.03.12  # Docker service

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
