version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18  # Ensure it's Node.js 18+ (adjust based on Nuxt requirements)
    steps:
      - checkout
      - run:
          name: Check Node.js Version
          command: node -v
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Prepare Nuxt
          command: npx nuxt prepare  # Ensure correct command
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Nuxt Project
          command: npm run build
