version: 2.1

executors:
  node-executor:
    docker:
      - image: docker:19.03.12  # Docker image for Docker commands
    working_directory: ~/repo

jobs:
  build:
    docker:
      - image: docker:19.03.12  # Docker image for build job
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install curl and docker-compose
          command: |
            apt-get update && apt-get install -y curl  # Install curl
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version  # Verify docker-compose installation
      - run:
          name: Set up Docker
          command: |
            docker --version
            docker-compose --version
      - run:
          name: Build Docker image
          command: |
            docker-compose -f docker-compose.yml build
      - run:
          name: Run tests (if any)
          command: |
            docker-compose -f docker-compose.yml run nuxt npm run test

  deploy:
    docker:
      - image: docker:19.03.12  # Docker image for deploy job
    steps:
      - checkout
      - run:
          name: Install curl and docker-compose
          command: |
            apt-get update && apt-get install -y curl  # Install curl
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version  # Verify docker-compose installation
      - run:
          name: Set up Docker and Docker Compose
          command: |
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
