version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - run:
          name: Build and start services
          command: |
            cd ~/repo
            docker-compose build
            docker-compose up -d
      - run:
          name: Wait for application to be ready
          command: |
            sleep 30
            curl -f http://localhost:3000 || exit 1
      - run:
          name: Stop services
          command: |
            cd ~/repo
            docker-compose down

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - master
