apiVersion: v1
kind: Service
metadata:
  name: nuxt3-service
spec:
  selector:
    app: nuxt3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
